#!/bin/bash

echo "🌐 Video Downloader - Frontend Deployment Setup"
echo "==============================================="
echo ""
echo "⚠️  IMPORTANT: Deploy backend first!"
echo ""
echo "📝 Step 1: Update Backend URL"
echo "   Open: src/App.jsx"
echo "   Line 11: Replace with your Render backend URL"
echo ""
echo "📝 Step 2: Deploy to Vercel"
echo ""
echo "Option A - Vercel CLI (Recommended):"
echo "   npm install -g vercel"
echo "   vercel login"
echo "   vercel"
echo ""
echo "Option B - Vercel Dashboard:"
echo "   1. Go to https://vercel.com"
echo "   2. Click 'Add New' → 'Project'"
echo "   3. Import this folder"
echo "   4. Click 'Deploy'"
echo ""
echo "Option C - Build & Manual Deploy:"
echo "   npm run build"
echo "   # Then upload 'dist' folder to Netlify/Vercel"
echo ""
echo "✅ Files ready:"
echo "   ✅ vercel.json"
echo "   ✅ package.json"
echo "   ✅ All source files"
echo ""
